name: Deploy

on:
  push:
    branches:
      - main

jobs:
  validate-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Validar HTML
        uses:  validator/validator-action@v3
        with:
          root: .
          format: text
          log_level: INFO

  deploy:
    needs: validate-html
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar gh-pages
        uses: actions/configure-pages@v3

      - name: Publicar en GitHub Pages
        uses: actions/upload-pages-artifact@v2