name: Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Instalar html-validate
        run: npm install -g html-validate

      - name: Validar archivos HTML
        run: html-validate "**/*.html"

      - name: Configurar Pages
        uses: actions/configure-pages@v3

      - name: Construir con Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: Subir artefacto
        uses: actions/upload-pages-artifact@v2

      - name: Desplegar a GitHub Pages
        uses: actions/deploy-pages@v2