name: Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Instalar herramientas
        run: |
          npm install -g html-validate
          gem install jekyll bundler

      - name: Validar HTML
        run: html-validate "**/*.html" || echo "Advertencia: Hay problemas de HTML, pero continuamos"

      - name: Configurar Pages
        uses: actions/configure-pages@v3

      - name: Construir sitio
        run: |
          jekyll build --destination _site || mkdir -p _site && cp -r * _site/

      - name: Subir artefacto de Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: _site

      - name: Desplegar a GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1